steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/streamlit-image', '.']

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/streamlit-image']

options:
  logging: NONE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  

