steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/streamlit-app', '.']

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/streamlit-app']

images:
  - 'gcr.io/$PROJECT_ID/streamlit-app'

options:
  logging: CLOUD_LOGGING_ONLY
  

